complaint_management_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("managers/", include("managers.urls")),
    path("", include("core.urls")),
]

core/urls.py
from django.urls import path
from .views import index, loginView, logoutView, register, viewComplaint, editComplaint, deleteComplaint, resolved, complaints, unresolved, editAccount

app_name = "core"
urlpatterns = [
    path("", index, name = "index"),
    path("login/", loginView, name = "login"),
    path("register/", register, name = "register"),
    path("logout/", logoutView, name = "logout"),
    path("edit-account/", editAccount, name = "editAccount"),
    path("complaints/", complaints, name = "complaints"),
    path("complaint/<slug:slug>/", viewComplaint, name = "viewComplaint"),
    path("resolved/<slug:slug>/", resolved, name = "resolved"),
    path("unresolved/<slug:slug>/", unresolved, name = "unresolved"),
    path("edit-complaint/<slug:slug>/", editComplaint, name = "editComplaint"),
    path("delete-complaint/<slug:slug>/", deleteComplaint, name = "deleteComplaint"),
]

managers/urls.py
from django.urls import path
from .views import loginView, logoutView, dashboard, newAdmin, removeAdmin, editAdmin

app_name = "managers"
urlpatterns = [
    path("login/", loginView, name = "managerLogin"),
    path("logout/", logoutView, name = "managerLogout"),
    path("new-admin/", newAdmin, name = "newAdmin"),
    path("edit-admin/<slug:slug>/", editAdmin, name = "editAdmin"),
    path("remove-user/", removeAdmin, name = "removeAdmin"),
    path("dashboard/", dashboard, name = "managerDashboard"),
]

managers/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from common.utils import isValidInput, cleanInput
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from common.decorators import logoutRequired, onlyManager
from core.models import ManagerAdmin

User = get_user_model()

@logoutRequired
def loginView(request):
	if request.method == "POST":
		email = request.POST.get("email")
		password = request.POST.get("password")
		user = authenticate(
			email = email,
			password = password
		)

		print(user)
		if user == None or not user.isManager:
			messages.error(request, "Invalid Credentials.")
			return render(request, "managers/login.html", {})

		login(request, user)
		messages.success(request, f"You have been logged in successfully!")
		return HttpResponseRedirect("/managers/dashboard/")

	return render(request, "managers/login.html", {})

@login_required(login_url = "/managers/login/")
@onlyManager
def logoutView(request):
	logout(request)
	messages.success(request, f"You have been logged out successfully!")
	return HttpResponseRedirect("/managers/login/")

@login_required(login_url = "/managers/login/")
@onlyManager
def dashboard(request):
	manager = request.user
	admins = [admin.admin for admin in manager.admins.all().order_by("admin__firstName")]
	counts = []

	for admin in admins:
		complaints = list(set([a.complaint for a in admin.replies.all()]))
		resolved, resolving = 0, 0

		for c in complaints:
			if c.status:
				resolved += 1
			else:
				resolving += 1

		counts.append({"resolved" : resolved, "resolving" : resolving})

	return render(request, "managers/manager-dashboard.html", {
		"manager": manager,
		"admins": zip(admins, counts)
	})

@login_required(login_url = "/managers/login/")
@onlyManager
def newAdmin(request):
	if request.method == "POST":
		firstName = request.POST.get("firstName")
		lastName = request.POST.get("lastName", "")
		email = request.POST.get("email")
		password = request.POST.get("password")
		confirmPassword = request.POST.get("confirmPassword")
		error = False
		last = {}

		if isValidInput(firstName):
			firstName = cleanInput(firstName)
			last["firstName"] = firstName
		else:
			messages.error(request, "Invalid First Name")
			error = True

		lastName = cleanInput(lastName)
		last["lastName"] = lastName

		if isValidInput(email):
			email = cleanInput(email)

			if User.objects.filter(email = email).exists():
				messages.error(request, "Email already exists.")	
				last["email"] = email
				return render(request, "managers/new-admin.html", {
					"last": last
				})
			
			last["email"] = email
		else:
			messages.error(request, "Invalid Email")
			error = True

		if isValidInput(password):
			password = cleanInput(password)
		else:
			messages.error(request, "Invalid Password")
			error = True

		if isValidInput(confirmPassword):
			confirmPassword = cleanInput(confirmPassword)
		else:
			messages.error(request, "Invalid Confirm Password")
			error = True

		if password != confirmPassword:
			messages.error(request, "Passwords don't match")
			error = True

		if not error:
			user = User(
				email = email,
				firstName = firstName,
				lastName = lastName,
				isAdmin = True,
			)
			user.set_password(password)
			user.save()
			manager = request.user
			ManagerAdmin.objects.create(admin = user, manager = manager)
			messages.success(request, f"New admin has been created successfully!")
			return HttpResponseRedirect("/managers/dashboard")

		return render(request, "managers/new-admin.html", {
			"last": last
		})

	return render(request, "managers/new-admin.html", {})

@login_required(login_url = "/managers/login/")
@onlyManager
def removeAdmin(request):
	if request.method == "POST":
		slug = request.POST.get("slug")

		if slug == None:
			messages.error(request, "Invalid URL.")
			return HttpResponseRedirect("/managers/dashboard/")

		manager = request.user
		user = User.objects.filter(slug = slug)

		if not user.exists():
			messages.error(request, "No such admin exists.")
			return HttpResponseRedirect("/managers/dashboard/")

		user = user.first()

		if not ManagerAdmin.objects.filter(admin = user, manager = manager).exists():
			messages.error(request, "Admin was not created by you.")
			return HttpResponseRedirect("/managers/dashboard/")

		user.delete()
		messages.success(request, "Admin removed successfully!")	
		
	return HttpResponseRedirect("/managers/dashboard/")	 

@login_required(login_url = "/managers/login/")
@onlyManager
def editAdmin(request, slug):
	user = User.objects.filter(slug = slug)

	if not user.exists():
		messages.error(request, "No such admin exists.")
		return HttpResponseRedirect("/managers/dashboard/")	
	
	user = user.first()

	if request.method == "POST":
		firstName = request.POST.get("firstName").strip()
		email = request.POST.get("email").strip()
		
		if isValidInput(firstName):
			firstName = cleanInput(firstName)
		else:
			firstName = user.firstName
			messages.error(request, "Invalid First Name")

		if isValidInput(email):
			email = cleanInput(email)

			if User.objects.filter(email = email).exists():
				messages.error(request, "Email already exists.")
				email = user.email
		else:
			messages.error(request, "Invalid Email")
			email = user.email

		lastName = request.POST.get("lastName").strip()
		user.email = email
		user.firstName = firstName
		user.lastName = lastName
		user.save()
		messages.success(request, "Changes saved successfully!")

	return render(request, "managers/edit-admin.html", {
		"user": user,
	})

managers/templates/managers/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    <title>{% block title %}{% endblock %} | CMS</title>
    {% block head %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-light bg-light">
        <div class="container ps-4 pe-4">
            <div class="d-flex align-items-center justify-content-between w-100">
                <a href="{% url 'managers:managerDashboard' %}" class="text-decoration-none text-dark">
                    <h4 class="d-flex pe-2 m-0">CMS</h4>
                </a>
                <div class="d-flex align-items-center p-0">
                    {% if request.user.is_authenticated %}
                        <a class="text-decoration-none active ms-3 btn-sm btn btn-danger" href="{% url 'managers:managerLogout' %}">Log Out</a>
                    {% else %}
                        <a class="text-decoration-none btn-sm btn btn-dark" href="{% url 'managers:managerLogin' %}">Log In</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    <div class="container ps-4 pe-4">
    {% block content %}
    {% endblock %}
    </div>
    <div id="messages" class="toast-container p-4 position-absolute bottom-0 end-0">
        {% if messages %}
            {% for message in messages %}
                <div class="toast align-items-center" role="alert" aria-live="assertive" aria-atomic="true">
                    <div class="d-flex">
                        <div class="toast-body">{{ message }}</div>
                        <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
<script>
    $(document).ready(function(){
        $('.toast').toast('show');
    });
</script>
{% block scripts %}
{% endblock %}
</html>

managers/templates/managers/edit-admin.html
{% extends "managers/base.html" %}
{% load static %}

{% block title %}
User Register
{% endblock %}

{% block head %}
{% endblock %}

{% block content %}
<div class="d-flex align-items-center justify-content-center h-100">
    <div class="card mt-4 mb-4 w-100 mxw-500">
        <div class="card-body">
            <form action="" class="form mb-3" method="POST">
                <h4>Edit Admin</h4>
                <hr>
                <div class="mb-3">
                    <label for="firstName" class="form-label">First Name</label>
                    <input type="text" value="{{ user.firstName }}" name="firstName" placeholder="Enter your first name" class="form-control" required>
                </div>
                <div class="mb-3">
                    <label for="lastName" class="form-label">Last Name</label>
                    <input type="text" value="{{ user.lastName }}" name="lastName" placeholder="Enter your last name" class="form-control">
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" value="{{ user.email }}" disabled name="email" placeholder="Enter your email" class="form-control" required>
                </div>
                {% csrf_token %}
                <input type="submit" value="Save Changes" class="btn btn-success w-100">
            </form>            
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

managers/templates/managers/login.html
{% extends "managers/base.html" %}
{% load static %}

{% block title %}
Manager Login
{% endblock %}

{% block head %}
{% endblock %}

{% block content %}
<div class="d-flex align-items-center justify-content-center h-100">
    <div class="card mt-4 mb-4 w-100 mxw-500">
        <div class="card-body">
            <form action="" class="form mb-3" method="POST">
                <h4>Manager Login</h4>
                <hr>
                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" name="email" placeholder="Enter your email" class="form-control">
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" name="password" placeholder="Enter your password" class="form-control">
                </div>
                {% csrf_token %}
                <input type="submit" value="Log In" class="btn btn-success w-100">
            </form>
            <a href="" class="text-decoration-none">Forgot password?</a>
            <hr>
            <a href="{% url 'core:login' %}" class="btn btn-danger mt-3 w-100">Login as User</a>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

managers/templates/managers/manager-dashboard.html
{% extends 'managers/base.html'%}
{% load static %}

{% block head %}
{% endblock %}

{% block content %}
<div class="container mt-5 mb-5 p-0">
    <div class="btn-group">
        <a href="{% url 'managers:newAdmin' %}" class="btn btn-success">New Admin</a>
    </div>
    <div class="card mt-3 rounded-0">
        <div class="card-header">
            <h4>Resolvers</h4>
            <p class="mb-0">List of all the Resolvers managed by you</p>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped border border-top-0">
            <thead class="thead-dark">
                <tr>
                    <th class="text-center" scope="col">S. No</th>
                    <th class="text-center" scope="col">Full Name</th>
                    <th class="text-center" scope="col">Email</th>
                    <th class="text-center" scope="col">Resolving</th>
                    <th class="text-center" scope="col">Resolved</th>
                    <th class="text-center" scope="col">Joined On</th>
                    <th class="text-center" scope="col">Actions</th>
                </tr>
            </thead>
            <tbody class="border">
                {% for admin, counts in admins %}
                    <tr>
                        <td class="text-center align-middle">{{ forloop.counter }}</td>
                        <td class="text-center align-middle">{{ admin.getName }}</td>
                        <td class="text-center align-middle">{{ admin.email }}</td>
                        <td class="text-center align-middle">{{ counts.resolving }}</td>
                        <td class="text-center align-middle">{{ counts.resolved }}</td>
                        <td class="text-center align-middle">{{ admin.dateJoined|date:'m F, Y' }}</td>
                        <td class="text-center align-middle">
                            <div class="btn-group">
                                <a href="{% url 'managers:editAdmin' admin.slug %}" class="btn btn-sm btn-dark">Edit</a>
                                <button class="btn btn-sm btn-danger"><form action="{% url 'managers:removeAdmin' %}" method="POST">{% csrf_token %}<input type="hidden" name="slug" value="{{ admin.slug }}"><input type="submit" class="bg-transparent border-0 text-white" style="cursor: pointer;" value="Remove"></form></button>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

managers/templates/managers/new-admin.html
{% extends "managers/base.html" %}
{% load static %}

{% block title %}
User Register
{% endblock %}

{% block head %}
{% endblock %}

{% block content %}
<div class="d-flex align-items-center justify-content-center h-100">
    <div class="card mt-4 mb-4 w-100 mxw-500">
        <div class="card-body">
            <form action="" class="form mb-3" method="POST">
                <h4>Admin Registration</h4>
                <hr>
                <div class="mb-3">
                    <label for="firstName" class="form-label">First Name</label>
                    <input type="text" value="{{ last.firstName }}" name="firstName" placeholder="Enter your first name" class="form-control" required>
                </div>
                <div class="mb-3">
                    <label for="lastName" class="form-label">Last Name</label>
                    <input type="text" value="{{ last.lastName }}" name="lastName" placeholder="Enter your last name" class="form-control">
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" value="{{ last.email }}" name="email" placeholder="Enter your email" class="form-control" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" name="password" placeholder="Enter your password" class="form-control" required>
                </div>
                <div class="mb-3">
                    <label for="confirmPassword" class="form-label">Confirm Password</label>
                    <input type="password" name="confirmPassword" placeholder="Re-enter your password" class="form-control" required>
                </div>
                {% csrf_token %}
                <input type="submit" value="Register" class="btn btn-success w-100">
            </form>            
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}