complaint_management_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("managers/", include("managers.urls")),
    path("", include("core.urls")),
]

core/urls.py
from django.urls import path
from .views import index, loginView, logoutView, register, viewComplaint, editComplaint, deleteComplaint, resolved, complaints, unresolved, editAccount

app_name = "core"
urlpatterns = [
    path("", index, name = "index"),
    path("login/", loginView, name = "login"),
    path("register/", register, name = "register"),
    path("logout/", logoutView, name = "logout"),
    path("edit-account/", editAccount, name = "editAccount"),
    path("complaints/", complaints, name = "complaints"),
    path("complaint/<slug:slug>/", viewComplaint, name = "viewComplaint"),
    path("resolved/<slug:slug>/", resolved, name = "resolved"),
    path("unresolved/<slug:slug>/", unresolved, name = "unresolved"),
    path("edit-complaint/<slug:slug>/", editComplaint, name = "editComplaint"),
    path("delete-complaint/<slug:slug>/", deleteComplaint, name = "deleteComplaint"),
]

core/models.py
import random
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class UserManager(BaseUserManager):
    def create_user(self, email, firstName, password = None):
        if not email:
            raise ValueError("Users must have an email address.")

        user = self.model(
            email = self.normalize_email(email),
            firstName = firstName
        )

        user.set_password(password)
        user.save(using = self._db)
        return user

    def create_superuser(self, email, firstName, password):
        user = self.create_user(
            email = self.normalize_email(email),
            firstName = firstName,
            password = password
        )

        user.isAdmin = True
        user.isSuperuser = True
        user.save(using = self._db)
        return user

def generateUserSlug():
    length = 100
    domain = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

    while True:
        slug = "".join(random.choices(domain, k = length))

        if not User.objects.filter(slug = slug).exists():
            return slug

class User(AbstractBaseUser):
    email = models.EmailField(max_length = 200, unique = True)
    firstName = models.CharField(max_length = 100)
    lastName = models.CharField(max_length = 100, blank = True)
    dateJoined = models.DateTimeField(verbose_name = "Date of Joining", auto_now_add = True)
    dateLastLogin = models.DateTimeField(verbose_name = "Date of Last Login", auto_now = True)
    active = models.BooleanField(default = True)
    isSuperuser = models.BooleanField(default = False)
    isAdmin = models.BooleanField(default = False)
    isManager = models.BooleanField(default = False)
    slug = models.SlugField(max_length = 100, unique = True, default = generateUserSlug)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["firstName"]

    objects = UserManager()

    class Meta:
        db_table = "User"

    @property
    def is_staff(self):
        return self.isSuperuser

    @property
    def is_superuser(self):
        return self.isSuperuser

    @property
    def is_admin(self):
        return self.isAdmin

    @property
    def isAuthenticated(self):
        return self.is_authenticated

    @property
    def isAnonymous(self):
        return self.is_anonymous

    def __str__(self):
        return f"{self.email} | {self.getName()}"

    def has_perm(self, perm, obj = None):
        return self.isSuperuser

    def has_module_perms(self, app_label):
        return True

    def getName(self):
        return " ".join([self.firstName, self.lastName])

class ManagerAdmin(models.Model):
    manager = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "admins")
    admin = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "manager")

    class Meta:
        verbose_name = "ManagerAdmin"
        verbose_name_plural = "ManagerAdmins"

def generateComplaintSlug():
    length = 100
    domain = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

    while True:
        slug = "".join(random.choices(domain, k = length))

        if not Complaint.objects.filter(slug = slug).exists():
            return slug

class Complaint(models.Model):
    title = models.CharField(max_length = 500)
    complaint = models.TextField()
    author = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "complaints")
    status = models.BooleanField(default = False)
    dateCreated = models.DateTimeField(auto_now_add = True)
    dateUpdated = models.DateTimeField(auto_now = True)
    slug = models.SlugField(max_length = 100, unique = True, default = generateComplaintSlug)

    class Meta:
        db_table = "complaints"

class Tag(models.Model):
    name = models.CharField(max_length = 200)
    slug = models.CharField(max_length = 200)
    dateCreated = models.DateTimeField(auto_now_add = True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Tag, self).save(*args, **kwargs)
    
    class Meta:
        db_table = "tags"

class ComplaintTag(models.Model):
    complaint = models.ForeignKey(Complaint, on_delete = models.CASCADE, related_name = "tags")
    tag = models.ForeignKey(Tag, on_delete = models.CASCADE, related_name = "complaints")
    dateCreated = models.DateTimeField(auto_now_add = True)
    
    class Meta:
        db_table = "complaint_tags"
        verbose_name = "ComplaintTag"
        verbose_name_plural = "ComplaintTags"

class Reply(models.Model):
    reply = models.TextField()
    complaint = models.ForeignKey(Complaint, on_delete = models.CASCADE, related_name = "replies")
    author = models.ForeignKey(User, on_delete = models.SET_NULL, null = True, related_name = "replies")
    dateCreated = models.DateTimeField(auto_now_add = True)
    dateUpdated = models.DateTimeField(auto_now = True)
    
    class Meta:
        db_table = "replies"

core/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField

User = get_user_model()

class UserCreationForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput)
    password_2 = forms.CharField(label = "Confirm Password", widget = forms.PasswordInput)

    class Meta:
        model = User
        fields = ["email", "firstName", "lastName", "isAdmin", "isManager", "active", "isSuperuser", "slug"]

    def clean(self):
        cleanedData = super().clean()
        password = cleanedData.get("password")
        password_2 = cleanedData.get("password_2")

        if password is None:
            self.add_error("password", "Password is empty")

        if password_2 is None:
            self.add_error("password_2", "Confirm password is empty")

        if password is not None and password != password_2:
            self.add_error("password_2", "Passwords don't match")

        return cleanedData

    def save(self, commit = True):
        user = super().save(commit = False)
        user.set_password(self.cleaned_data["password"])

        if commit:
            user.save()

        return user

class UserEditForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()
    slug = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ["email", "password", "firstName", "lastName", "isAdmin", "isManager", "active", "isSuperuser", "slug"]
    def clean_password(self):
        return self.initial["password"]

core/views.py
from django.core import paginator
from django.http.response import JsonResponse
from django.db.models import Q
from django.shortcuts import render
from django.utils import timezone
from .models import Complaint, Tag, ComplaintTag, Reply
from django.contrib import messages
from django.http import HttpResponseRedirect
from common.utils import isValidInput, cleanInput
from common.decorators import loginRequired, logoutRequired, onlyAdmin, onlyUser, onlyPostRequest, notManager
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

User = get_user_model()

@loginRequired
@notManager
def index(request):
    user = request.user

    if user.isAdmin:
        complaintIDs = Reply.objects.filter(author = user).values_list("complaint").distinct()
        complaints = Complaint.objects.filter(id__in = complaintIDs)
        return render(request, "core/index.html", {
            "complaints": complaints,
        })
    else:
        if request.method == "POST":
            last = {}
            error = False
            title = request.POST.get("title")
            complaint = request.POST.get("complaint")
            tags = request.POST.getlist("tag")

            if isValidInput(title):
                title = cleanInput(title)
                last["title"] = title
            else:
                messages.error(request, "Invalid Title")
                error = True

            if isValidInput(complaint):
                complaint = cleanInput(complaint)
                last["complaint"] = complaint
            else:
                messages.error(request, "Invalid Complaint")
                error = True

            last["tag"] = []
            tagError = False

            for i in range(len(tags)):
                if isValidInput(tags[i]):
                    tags[i] = cleanInput(tags[i].lower())
                    last["tag"].append(tags[i].lower())
                else:                
                    tagError = True
                    error = True

            if tagError:
                messages.error(request, "Invalid Tag")

            if not error:
                complaint = Complaint.objects.create(
                    title = title,
                    complaint = complaint,
                    author = user
                )
                
                for tag in set(tags):
                    tagObject, created = Tag.objects.get_or_create(name = tag)
                    ComplaintTag.objects.create(
                        complaint = complaint,
                        tag = tagObject
                    )
            
                messages.success(request, "Complaint added successfully!")
            else:
                return render(request, "core/index.html", {
                    "complaints": Complaint.objects.filter(author = user),
                    "last": last
                })

        return render(request, "core/index.html", {
            "complaints": Complaint.objects.filter(author = user),
        })

@logoutRequired
def register(request):
    if request.method == "POST":
        firstName = request.POST.get("firstName")
        lastName = request.POST.get("lastName", "")
        email = request.POST.get("email")
        password = request.POST.get("password")
        confirmPassword = request.POST.get("confirmPassword")
        error = False
        last = {}

        if isValidInput(firstName):
            firstName = cleanInput(firstName)
            last["firstName"] = firstName
        else:
            messages.error(request, "Invalid First Name")
            error = True

        lastName = cleanInput(lastName)
        last["lastName"] = lastName

        if isValidInput(email):
            email = cleanInput(email)
            last["email"] = email
        else:
            messages.error(request, "Invalid Email")
            error = True

        if isValidInput(password):
            password = cleanInput(password)
        else:
            messages.error(request, "Invalid Password")
            error = True

        if isValidInput(confirmPassword):
            confirmPassword = cleanInput(confirmPassword)
        else:
            messages.error(request, "Invalid Confirm Password")
            error = True

        if password != confirmPassword:
            messages.error(request, "Passwords don't match")
            error = True

        if not error:
            user = User(
                email = email,
                firstName = firstName,
                lastName = lastName
            )
            user.set_password(password)
            user.save()
            messages.success(request, f"Hi {firstName}, your account has been created successfully!")
            return HttpResponseRedirect("/login/")
        else:
            return render(request, "core/register.html", {
                "last": last
            })

    return render(request, "core/register.html", {})

@loginRequired
def editAccount(request):
    user = request.user

    if request.method == "POST":
        firstName = request.POST.get("firstName")
        lastName = request.POST.get("lastName", "")

        if isValidInput(firstName):
            firstName = cleanInput(firstName)
        else:
            messages.error(request, "Invalid First Name")
            firstName = user.firstName

        lastName = cleanInput(lastName)
        user.firstName = firstName
        user.lastName = lastName
        user.save()
        messages.success(request, f"Changes saved successfully!")

    return render(request, "core/edit-account.html", {
        "user": user
    })

@logoutRequired
def loginView(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        user = authenticate(
            email = email,
            password = password
        )

        if user == None or user.isManager:
            messages.error(request, "Invalid Credentials.")
            return render(request, "core/login.html", {})        
        
        login(request, user)
        messages.success(request, f"You have been logged in successfully!")
        return HttpResponseRedirect("/")

    return render(request, "core/login.html", {})

@loginRequired
@notManager
def logoutView(request):
    logout(request)
    messages.success(request, f"You have been logged out successfully!")
    return HttpResponseRedirect("/")

@loginRequired
@onlyAdmin
def complaints(request):
    query = request.GET.get("query", "")
    all = request.GET.get("all") == "on"

    if isValidInput(query):
        cIDs = ComplaintTag.objects.filter(
            Q(tag__name__icontains = query) |
            Q(complaint__title__icontains = query)
        ).values_list("complaint__id").distinct()

        if all:
            complaints = Complaint.objects.filter(id__in = cIDs)
        else:
            complaints = Complaint.objects.filter(status = False).filter(id__in = cIDs)
    else:
        if all:
            complaints = Complaint.objects.all()    
        else:
            complaints = Complaint.objects.filter(status = False)    

    page = request.GET.get("page", 1)
    paginator = Paginator(complaints, 20)

    try:
        complaints = paginator.page(page)
    except PageNotAnInteger:
        complaints = paginator.page(1)
    except EmptyPage:
        complaints = paginator.page(paginator.num_pages)

    return render(request, "core/complaints.html", {
        "complaints": complaints,
        "all": all,
        "query": query
    })

@loginRequired
@onlyAdmin
@onlyPostRequest
def resolved(request, slug):
    complaint = Complaint.objects.filter(slug = slug)

    if complaint.exists():
        complaint = complaint.first()
        complaint.status = True
        complaint.save()
        return HttpResponseRedirect(f"/complaint/{slug}/")
    else:
        return HttpResponseRedirect("/")

@loginRequired
@onlyPostRequest
def unresolved(request, slug):
    user = request.user
    complaint = Complaint.objects.filter(slug = slug)

    if complaint.exists() and (user.isAdmin or complaint.first().author == user):
        complaint = complaint.first()
        complaint.status = False
        complaint.save()
        return HttpResponseRedirect(f"/complaint/{slug}/")
    else:
        return HttpResponseRedirect("/")

@loginRequired
@notManager
def viewComplaint(request, slug):
    user = request.user
    complaint = Complaint.objects.filter(slug = slug)

    if complaint.exists():
        complaint = complaint.first()

        if request.method == "POST" and (user.isAdmin or user == complaint.author):
            reply = request.POST.get("reply")
            Reply.objects.create(
                reply = reply,
                author = user,
                complaint = complaint,
            )

        return render(request, "core/complaint.html", {
            "complaint": complaint,
            "replies": Reply.objects.filter(complaint = complaint).order_by("dateCreated"),
            "today": timezone.now()
        })
    else:
        messages.error(request, "Complaint doesn't exists.")
        return HttpResponseRedirect("/")

@loginRequired
@onlyUser
def editComplaint(request, slug):
    complaint = Complaint.objects.filter(
        author = request.user,
        slug = slug
    )

    if not complaint.exists():
        messages.error(request, "Complaint doesn't exists.")
        return HttpResponseRedirect("/")

    complaint = complaint.first()

    if request.method == "POST":
        title = request.POST.get("title")
        complaintText = request.POST.get("complaint")
        tags = request.POST.getlist("tag")

        if isValidInput(title):
            title = cleanInput(title)
        else:
            title = complaint.title
            messages.error(request, "Invalid Title")

        if isValidInput(complaintText):

core/templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    <title>{% block title %}{% endblock %} | CMS</title>
    {% block head %}
    {% endblock %}
</head>
<body>
    <nav class="navbar navbar-light bg-light">
        <div class="container ps-4 pe-4">
            <div class="d-flex align-items-center justify-content-between w-100">
                <a href="{% url 'core:index' %}" class="text-decoration-none text-dark">
                    <h4 class="d-flex pe-2 m-0">CMS</h4>
                </a>
                <div class="d-flex align-items-center p-0">
                    <a class="text-decoration-none active ms-3" href="{% url 'core:index' %}">Home</a>
                    {% if request.user.isAdmin %}
                        <a class="text-decoration-none active ms-3" href="{% url 'core:complaints' %}">Complaints</a>
                    {% endif %}
                    {% if request.user.is_authenticated %}
                        <a class="text-decoration-none active ms-3" href="{% url 'core:editAccount' %}">Account</a>
                        <a class="text-decoration-none active ms-3 btn-sm btn btn-danger" href="{% url 'core:logout' %}">Log Out</a>
                    {% else %}
                    <div class="btn-group ms-3">
                        <a class="text-decoration-none btn-sm btn btn-danger" href="{% url 'core:register' %}">Register</a>
                        <a class="text-decoration-none btn-sm btn btn-dark" href="{% url 'core:login' %}">Log In</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    <div class="container ps-4 pe-4">
    {% block content %}
    {% endblock %}
    </div>
    <div id="messages" class="toast-container p-4 position-absolute bottom-0 end-0">
        {% if messages %}
            {% for message in messages %}
                <div class="toast align-items-center" role="alert" aria-live="assertive" aria-atomic="true">
                    <div class="d-flex">
                        <div class="toast-body">{{ message }}</div>
                        <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
<script>
    $(document).ready(function(){
        $('.toast').toast('show');
    });
</script>
{% block scripts %}
{% endblock %}
</html>

core/templates/core/complaint.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}
{{ complaint.title }}
{% endblock %}

{% block head %}
{% endblock %}

{% block content %}
<div class="d-flex flex-column pt-3">
    <div class="card">
        <div class="card-header">
            <h5>Complaint</h5>
        </div>
        <card class="card-body">
            <p>{{ complaint.title }}</p>
            <hr>
            <div class="d-flex align-items-center flex-wrap w-100">
                <button class="m-1 btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#complaint" aria-expanded="false" aria-controls="complaint">
                    View Description
                </button>
                <button class="m-1 btn btn-dark" type="button" data-bs-toggle="collapse" data-bs-target="#tags" aria-expanded="false" aria-controls="tags">
                    View Tags
                </button>
                {% if request.user.isAdmin and not complaint.status %}
                    <form action="{% url 'core:resolved' complaint.slug %}" method="POST">
                        {% csrf_token %}
                        <input type="submit" value="Mark As Resolved" class="m-1 btn btn-success">
                    </form>
                {% endif %}
                {% if complaint.status %}
                    <form action="{% url 'core:unresolved' complaint.slug %}" method="POST">
                        {% csrf_token %}
                        <input type="submit" value="Mark As Unresolved" class="m-1 btn btn-danger">
                    </form>
                {% endif %}
            </div>
            <div class="collapse mt-3" id="tags">
                <div class="card card-body">
                    <div class="d-flex flex-wrap justify-content-center">
                        {% for tag in complaint.tags.all %}
                            <button class="m-1 user-select-all btn btn-sm btn-light">{{ tag.tag.name }}</button>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="collapse mt-3" id="complaint">
                <div class="card card-body">
                    {{ complaint.complaint|linebreaks }}
                </div>
            </div>
        </card>
    </div>
    <hr class="mb-0">
    {% for r in replies %}
        <div class="card mt-3">
            <div class="card-header d-flex align-items-center justify-content-between">
                <p class="mb-1">{{ r.author.getName }}</p>
                {% if r.dateCreated == r.dateUpdated %}
                    <span class="badge bg-dark ms-3">{{ r.dateUpdated|timesince:today }} ago</span>
                {% else %}
                    <span class="badge bg-dark ms-3">{{ r.dateUpdated|timesince:today }} ago</span>
                {% endif %}
            </div>
            <div class="card-body pb-0">
                <p class="m-0">{{ r.reply|linebreaks }}</p>
            </div>
        </div>
    {% endfor %}
    <div class="card mt-3">
        <div class="card-body">
            <form action="" method="POST" class="form">
                <div class="mb-3">
                    <label for="complaint" class="form-label">Reply</label>
                    <textarea class="form-control" required name="reply" rows="7" placeholder="Enter your reply">{{ last.complaint }}</textarea>
                </div>
                {% csrf_token %}
                <input type="submit" value="Post Reply" class="btn btn-success">
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% endblock %}

core/templates/core/index.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}
Home
{% endblock %}

{% block head %}
{% endblock %}

{% block content %}
<div class="d-flex flex-column pt-3">
    {% if not request.user.isAdmin %}
        <div class="d-block">
            <button class="btn btn-primary mb-3" type="button" data-bs-toggle="collapse" data-bs-target="#complaintForm">New Complaint</button>
        </div>
        {% if last and last|length > 0 %}
            <div class="collapse mb-3 show" id="complaintForm">
        {% else %}
            <div class="collapse mb-3" id="complaintForm">
        {% endif %}
            <div class="card card-body">
                <form action="" class="form" method="POST">
                    <div class="mb-3">
                        <label for="title" class="form-label">Title</label>
                        <input type="text" name="title" class="form-control" value="{{ last.title }}" required placeholder="Enter a title">
                    </div>
                    <div class="mb-3">
                        <label for="complaint" class="form-label">Complaint</label>
                        <textarea class="form-control" required name="complaint" rows="7" placeholder="Enter you complaint">{{ last.complaint }}</textarea>
                    </div>
                    <div class="mb-3">
                        <label for="tags" class="form-label">Tags</label>
                        <div id="tags" class="form-control d-flex flex-wrap align-items-center justify-content-center pt-2 pb-3">
                            {% for tag in last.tag %}
                                <div class="btn-group border rounded m-2">
                                    <input type="button" class="btn btn-light" value="{{ tag }}">
                                    <input type="hidden" name="tag" value="{{ tag }}">
                                    <button type="button" class="btn btn-light" onclick="removeParent(this);">✕</button>
                                </div>
                            {% endfor %}
                            <input type="text" onkeydown="tagInputHandler(this);" class="form-control w-100 mt-2" placeholder="Enter a tag">
                        </div>
                    </div>
                    {% csrf_token %}
                    <input type="submit" value="Submit" class="btn btn-success">
                </form>
            </div>
        </div>
    {% endif %}
    <div class="d-flex flex-wrap justify-content-center pt-2 pb-2 complaints-space">
        <div class="table-responsive w-100 me-2 ms-2">
            <table class="table">
                <colgroup>
                    <col span="1" style="width: 5%;">
                    <col span="1" style="width: 60%;">
                    <col span="1" style="width: 10%;">
                    <col span="1" style="width: 25%;">
                </colgroup>
                <thead class="table-light">
                    <tr>
                        <th class="text-center align-middle">#</th>
                        <th class="align-middle">Title</th>
                        <th class="text-center align-middle">Resolved</th>
                        <th class="text-center align-middle">Actions</th>
                    </tr>
                    <tbody>
                        {% for complaint in complaints %}
                        <tr class="table-light">
                            <td class="text-center align-middle">{{ forloop.counter }}</td>
                            <td class="align-middle">{{ complaint.title }}</td>
                            <td class="text-center align-middle">
                                {% if complaint.status %}
                                    <img src="{% static 'images/tick.png' %}" class="table-cell-icon" alt="">
                                {% else %}
                                    <img src="{% static 'images/cross.png' %}" class="table-cell-icon" alt="">
                                {% endif %}
                            </td>
                            <td class="text-center align-middle">
                                <div class="btn-group">
                                    <a href="{% url 'core:viewComplaint' complaint.slug %}" class="w-100 btn btn-dark">View</a>
                                    {% if not request.user.isAdmin %}
                                        <a href="{% url 'core:editComplaint' complaint.slug %}" class="w-100 btn btn-success">Edit</a>
                                        <a href="{% url 'core:deleteComplaint' complaint.slug %}" class="w-100 btn btn-dark">Delete</a>
                                    {% endif %}
                                    <button type="button" class="w-100 btn btn-success" data-bs-toggle="collapse" data-bs-target="#complaint{{ forloop.counter }}">Tags</button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="4" class="collapse" id="complaint{{ forloop.counter }}">
                                <div class="d-flex flex-wrap justify-content-center">
                                    {% for tag in complaint.tags.all %}
                                        <button class="m-1 btn btn-sm btn-light">{{ tag.tag.name }}</button>
                                    {% endfor %}
                                </div>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td class="text-center" colspan="4">No Complaints</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </thead>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    function removeParent(element) {
        element.parentElement.remove();
    }

    function tagInputHandler(element) {
        if (event.keyCode == 13 && element.value.trim() != "") {
            const tagHTML = `<div class="btn-group border rounded m-2"><input type="button" class="btn btn-light" value="${element.value.trim()}"><input type="hidden" name="tag" value="${element.value.trim()}"><button type="button" class="btn btn-light" onclick="removeParent(this);">✕</button></div>`;
            element.insertAdjacentHTML("beforebegin", tagHTML);
            element.value = "";
        }
    }

    document.getElementById("complaintForm").onkeypress = function(event) {
    let key = event.charCode || event.keyCode || 0;     

    if (key == 13) {
      event.preventDefault();
    }
}
</script>
{% endblock %}

core/templates/core/template.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}
{% endblock %}

{% block head %}
{% endblock %}

{% block content %}
{% endblock %}

{% block scripts %}
{% endblock %}